language: objective-c
cache: cocoapods
podfile: Example/ios/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example/ios/
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/ios/Earth.xcworkspace -scheme Earth-Example -sdk iphonesimulator11.4 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
