language: objective-c
osx_image: xcode9.4
branches:
only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_WORKSPACE=Example/ios/Earth.xcworkspace
  - MACOS_WORKSPACE=Example/macos/Earth_Macos.xcworkspace
  - IOS_FRAMEWORK_SCHEME="Earth-Example"
  - MACOS_FRAMEWORK_SCHEME="Earth_Macos"
  matrix:
    - DESTINATION="OS=11.4,name=iPhone X"         WORKSPACE="IOS_WORKSPACE"  SCHEME="$IOS_FRAMEWORK_SCHEME"    RUN_TESTS="NO" BUILD_EXAMPLE="NO" POD_LINT="NO"
    - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"  WORKSPACE="IOS_WORKSPACE"  SCHEME="$IOS_FRAMEWORK_SCHEME"    RUN_TESTS="NO" BUILD_EXAMPLE="NO" POD_LINT="NO"
    - DESTINATION="OS=9.3,name=iPhone 6"          WORKSPACE="IOS_WORKSPACE"  SCHEME="$IOS_FRAMEWORK_SCHEME"    RUN_TESTS="NO" BUILD_EXAMPLE="NO" POD_LINT="NO"

    - DESTINATION="arch=x86_64"                   WORKSPACE="MACOS_WORKSPACE"  SCHEME="$MACOS_FRAMEWORK_SCHEME"  RUN_TESTS="NO" BUILD_EXAMPLE="NO"  POD_LINT="YES"
  before_install:
    - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  script:
    - set -o pipefail
    - xcodebuild -version
    - xcodebuild -showsdks

# Build Framework in Debug and Run Tests if specified
- if [ $RUN_TESTS == "YES" ]; then
    xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
  else
    xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
fi

# Build Framework in Release and Run Tests if specified
- if [ $RUN_TESTS == "YES" ]; then
    xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
  else
    xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
fi

# Build Example in Debug if specified
- if [ $BUILD_EXAMPLE == "YES" ]; then
    xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
fi

# Run `pod lib lint` if specified
- if [ $POD_LINT == "YES" ]; then
    pod lib lint;
fi

secure: "IgQwLNAYM5KDXpOTgCeKwt6PcvZys9ej/Gqng0Lfkw/7sxeuyrPeXpN1U74JF2/ZJT/GFJ2PzjV6uIC9tai6JdYxYIJDpwczVuXBifJLDkLAjVfiifjXR3p2jB1cVbrXx0yB2VLBujov/2eqiLs1lwjVAQQ6VIdo9wcT0v252JgOsF32zOrjlpuiK6FIFkQYxQlDbnScs72XfRS6Upx3RQR2NzmmjmpOw+q/1OJItFLs7eZ/YnRT2eoGCP0we4SoOuJPKhUGrfhgPb99eEp3tx/osOlWlv+ji82jcqpA1fqtJO/ljimV8GpGQK1Ibx79K9XtFTWDvl+nPMN9Brj9WJk2PGrYNPWkQ2dHyJoAG/4SYZzWE8DYek0LF2Ymuz/VsPfF08DMXvwxwEN+mL4fWS0WseSZvWZZVkE9NZuWLmtIY1GrhhFccZtqeb7UEIXo8fKe+8AOLE0oyE9DyWhMhQxIH65XJnqRbN81J9ViMwZw82TMWES8QEqv616DjirIJuSlo/CSB1m8jWjjsgzKYKsEXZiX/E4hJm/gr7wx2VBUhwedKDMEybWJTw8RxBFWQO3SSk+pmawJ604usyABuj6YoFpEQ7ui/02wcrF9Ia/7Ng1lfj56G39bBEY+iOJdQ6zvsDY9bFlkeKTE55yG5JVn3vxbRkfOy/phIXi9BiU="
